// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module mmult_accel_mmult_accel_Pipeline_copy_A_VITIS_LOOP_97_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmemA_AWVALID,
        m_axi_gmemA_AWREADY,
        m_axi_gmemA_AWADDR,
        m_axi_gmemA_AWID,
        m_axi_gmemA_AWLEN,
        m_axi_gmemA_AWSIZE,
        m_axi_gmemA_AWBURST,
        m_axi_gmemA_AWLOCK,
        m_axi_gmemA_AWCACHE,
        m_axi_gmemA_AWPROT,
        m_axi_gmemA_AWQOS,
        m_axi_gmemA_AWREGION,
        m_axi_gmemA_AWUSER,
        m_axi_gmemA_WVALID,
        m_axi_gmemA_WREADY,
        m_axi_gmemA_WDATA,
        m_axi_gmemA_WSTRB,
        m_axi_gmemA_WLAST,
        m_axi_gmemA_WID,
        m_axi_gmemA_WUSER,
        m_axi_gmemA_ARVALID,
        m_axi_gmemA_ARREADY,
        m_axi_gmemA_ARADDR,
        m_axi_gmemA_ARID,
        m_axi_gmemA_ARLEN,
        m_axi_gmemA_ARSIZE,
        m_axi_gmemA_ARBURST,
        m_axi_gmemA_ARLOCK,
        m_axi_gmemA_ARCACHE,
        m_axi_gmemA_ARPROT,
        m_axi_gmemA_ARQOS,
        m_axi_gmemA_ARREGION,
        m_axi_gmemA_ARUSER,
        m_axi_gmemA_RVALID,
        m_axi_gmemA_RREADY,
        m_axi_gmemA_RDATA,
        m_axi_gmemA_RLAST,
        m_axi_gmemA_RID,
        m_axi_gmemA_RFIFONUM,
        m_axi_gmemA_RUSER,
        m_axi_gmemA_RRESP,
        m_axi_gmemA_BVALID,
        m_axi_gmemA_BREADY,
        m_axi_gmemA_BRESP,
        m_axi_gmemA_BID,
        m_axi_gmemA_BUSER,
        A,
        K,
        mul_ln96_1,
        A_bram_address1,
        A_bram_ce1,
        A_bram_we1,
        A_bram_d1
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmemA_AWVALID;
input   m_axi_gmemA_AWREADY;
output  [63:0] m_axi_gmemA_AWADDR;
output  [0:0] m_axi_gmemA_AWID;
output  [31:0] m_axi_gmemA_AWLEN;
output  [2:0] m_axi_gmemA_AWSIZE;
output  [1:0] m_axi_gmemA_AWBURST;
output  [1:0] m_axi_gmemA_AWLOCK;
output  [3:0] m_axi_gmemA_AWCACHE;
output  [2:0] m_axi_gmemA_AWPROT;
output  [3:0] m_axi_gmemA_AWQOS;
output  [3:0] m_axi_gmemA_AWREGION;
output  [0:0] m_axi_gmemA_AWUSER;
output   m_axi_gmemA_WVALID;
input   m_axi_gmemA_WREADY;
output  [7:0] m_axi_gmemA_WDATA;
output  [0:0] m_axi_gmemA_WSTRB;
output   m_axi_gmemA_WLAST;
output  [0:0] m_axi_gmemA_WID;
output  [0:0] m_axi_gmemA_WUSER;
output   m_axi_gmemA_ARVALID;
input   m_axi_gmemA_ARREADY;
output  [63:0] m_axi_gmemA_ARADDR;
output  [0:0] m_axi_gmemA_ARID;
output  [31:0] m_axi_gmemA_ARLEN;
output  [2:0] m_axi_gmemA_ARSIZE;
output  [1:0] m_axi_gmemA_ARBURST;
output  [1:0] m_axi_gmemA_ARLOCK;
output  [3:0] m_axi_gmemA_ARCACHE;
output  [2:0] m_axi_gmemA_ARPROT;
output  [3:0] m_axi_gmemA_ARQOS;
output  [3:0] m_axi_gmemA_ARREGION;
output  [0:0] m_axi_gmemA_ARUSER;
input   m_axi_gmemA_RVALID;
output   m_axi_gmemA_RREADY;
input  [7:0] m_axi_gmemA_RDATA;
input   m_axi_gmemA_RLAST;
input  [0:0] m_axi_gmemA_RID;
input  [10:0] m_axi_gmemA_RFIFONUM;
input  [0:0] m_axi_gmemA_RUSER;
input  [1:0] m_axi_gmemA_RRESP;
input   m_axi_gmemA_BVALID;
output   m_axi_gmemA_BREADY;
input  [1:0] m_axi_gmemA_BRESP;
input  [0:0] m_axi_gmemA_BID;
input  [0:0] m_axi_gmemA_BUSER;
input  [63:0] A;
input  [31:0] K;
input  [63:0] mul_ln96_1;
output  [15:0] A_bram_address1;
output   A_bram_ce1;
output   A_bram_we1;
output  [7:0] A_bram_d1;

reg ap_idle;
reg m_axi_gmemA_RREADY;
reg A_bram_ce1;
reg A_bram_we1;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
reg   [0:0] icmp_ln96_reg_299;
reg    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln96_fu_149_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmemA_blk_n_R;
wire    ap_block_pp0_stage0;
reg    ap_block_pp0_stage0_11001;
wire   [15:0] add_ln99_fu_232_p2;
reg   [15:0] add_ln99_reg_303;
reg   [7:0] gmemA_addr_read_reg_308;
reg    ap_condition_exit_pp0_iter2_stage0;
wire   [63:0] zext_ln99_fu_254_p1;
reg   [15:0] k_fu_74;
wire   [15:0] add_ln97_fu_238_p2;
wire    ap_loop_init;
reg   [30:0] i_fu_78;
wire   [30:0] select_ln96_1_fu_194_p3;
reg   [63:0] indvar_flatten_fu_82;
wire   [63:0] add_ln96_1_fu_154_p2;
wire   [31:0] zext_ln97_fu_168_p1;
wire   [0:0] icmp_ln97_fu_172_p2;
wire   [30:0] add_ln96_fu_180_p2;
wire   [5:0] trunc_ln99_1_fu_206_p1;
wire   [7:0] trunc_ln99_fu_202_p1;
wire   [15:0] tmp_s_fu_210_p3;
wire   [15:0] tmp_32_fu_218_p3;
wire   [15:0] sub_ln99_fu_226_p2;
wire   [15:0] select_ln96_fu_186_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_done_reg = 1'b0;
end

mmult_accel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter2_stage0)) begin
            ap_enable_reg_pp0_iter3 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            i_fu_78 <= 31'd0;
        end else if (((icmp_ln96_reg_299 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            i_fu_78 <= select_ln96_1_fu_194_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_82 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln96_fu_149_p2 == 1'd0))) begin
            indvar_flatten_fu_82 <= add_ln96_1_fu_154_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            k_fu_74 <= 16'd0;
        end else if (((icmp_ln96_reg_299 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            k_fu_74 <= add_ln97_fu_238_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln96_reg_299 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        add_ln99_reg_303 <= add_ln99_fu_232_p2;
        gmemA_addr_read_reg_308 <= m_axi_gmemA_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
        icmp_ln96_reg_299 <= icmp_ln96_fu_149_p2;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        A_bram_ce1 = 1'b1;
    end else begin
        A_bram_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        A_bram_we1 = 1'b1;
    end else begin
        A_bram_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln96_fu_149_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln96_reg_299 == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter2_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter2_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln96_reg_299 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        gmemA_blk_n_R = m_axi_gmemA_RVALID;
    end else begin
        gmemA_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln96_reg_299 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axi_gmemA_RREADY = 1'b1;
    end else begin
        m_axi_gmemA_RREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign A_bram_address1 = zext_ln99_fu_254_p1;

assign A_bram_d1 = gmemA_addr_read_reg_308;

assign add_ln96_1_fu_154_p2 = (indvar_flatten_fu_82 + 64'd1);

assign add_ln96_fu_180_p2 = (i_fu_78 + 31'd1);

assign add_ln97_fu_238_p2 = (select_ln96_fu_186_p3 + 16'd1);

assign add_ln99_fu_232_p2 = (sub_ln99_fu_226_p2 + select_ln96_fu_186_p3);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((icmp_ln96_reg_299 == 1'd0) & (m_axi_gmemA_RVALID == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((icmp_ln96_reg_299 == 1'd0) & (m_axi_gmemA_RVALID == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = ((icmp_ln96_reg_299 == 1'd0) & (m_axi_gmemA_RVALID == 1'b0));
end

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign icmp_ln96_fu_149_p2 = ((indvar_flatten_fu_82 == mul_ln96_1) ? 1'b1 : 1'b0);

assign icmp_ln97_fu_172_p2 = (($signed(zext_ln97_fu_168_p1) < $signed(K)) ? 1'b1 : 1'b0);

assign m_axi_gmemA_ARADDR = 64'd0;

assign m_axi_gmemA_ARBURST = 2'd0;

assign m_axi_gmemA_ARCACHE = 4'd0;

assign m_axi_gmemA_ARID = 1'd0;

assign m_axi_gmemA_ARLEN = 32'd0;

assign m_axi_gmemA_ARLOCK = 2'd0;

assign m_axi_gmemA_ARPROT = 3'd0;

assign m_axi_gmemA_ARQOS = 4'd0;

assign m_axi_gmemA_ARREGION = 4'd0;

assign m_axi_gmemA_ARSIZE = 3'd0;

assign m_axi_gmemA_ARUSER = 1'd0;

assign m_axi_gmemA_ARVALID = 1'b0;

assign m_axi_gmemA_AWADDR = 64'd0;

assign m_axi_gmemA_AWBURST = 2'd0;

assign m_axi_gmemA_AWCACHE = 4'd0;

assign m_axi_gmemA_AWID = 1'd0;

assign m_axi_gmemA_AWLEN = 32'd0;

assign m_axi_gmemA_AWLOCK = 2'd0;

assign m_axi_gmemA_AWPROT = 3'd0;

assign m_axi_gmemA_AWQOS = 4'd0;

assign m_axi_gmemA_AWREGION = 4'd0;

assign m_axi_gmemA_AWSIZE = 3'd0;

assign m_axi_gmemA_AWUSER = 1'd0;

assign m_axi_gmemA_AWVALID = 1'b0;

assign m_axi_gmemA_BREADY = 1'b0;

assign m_axi_gmemA_WDATA = 8'd0;

assign m_axi_gmemA_WID = 1'd0;

assign m_axi_gmemA_WLAST = 1'b0;

assign m_axi_gmemA_WSTRB = 1'd0;

assign m_axi_gmemA_WUSER = 1'd0;

assign m_axi_gmemA_WVALID = 1'b0;

assign select_ln96_1_fu_194_p3 = ((icmp_ln97_fu_172_p2[0:0] == 1'b1) ? i_fu_78 : add_ln96_fu_180_p2);

assign select_ln96_fu_186_p3 = ((icmp_ln97_fu_172_p2[0:0] == 1'b1) ? k_fu_74 : 16'd0);

assign sub_ln99_fu_226_p2 = (tmp_s_fu_210_p3 - tmp_32_fu_218_p3);

assign tmp_32_fu_218_p3 = {{trunc_ln99_fu_202_p1}, {8'd0}};

assign tmp_s_fu_210_p3 = {{trunc_ln99_1_fu_206_p1}, {10'd0}};

assign trunc_ln99_1_fu_206_p1 = select_ln96_1_fu_194_p3[5:0];

assign trunc_ln99_fu_202_p1 = select_ln96_1_fu_194_p3[7:0];

assign zext_ln97_fu_168_p1 = k_fu_74;

assign zext_ln99_fu_254_p1 = add_ln99_reg_303;

endmodule //mmult_accel_mmult_accel_Pipeline_copy_A_VITIS_LOOP_97_1
