// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module mmult_accel_mmult_accel_Pipeline_VITIS_LOOP_120_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmemB_AWVALID,
        m_axi_gmemB_AWREADY,
        m_axi_gmemB_AWADDR,
        m_axi_gmemB_AWID,
        m_axi_gmemB_AWLEN,
        m_axi_gmemB_AWSIZE,
        m_axi_gmemB_AWBURST,
        m_axi_gmemB_AWLOCK,
        m_axi_gmemB_AWCACHE,
        m_axi_gmemB_AWPROT,
        m_axi_gmemB_AWQOS,
        m_axi_gmemB_AWREGION,
        m_axi_gmemB_AWUSER,
        m_axi_gmemB_WVALID,
        m_axi_gmemB_WREADY,
        m_axi_gmemB_WDATA,
        m_axi_gmemB_WSTRB,
        m_axi_gmemB_WLAST,
        m_axi_gmemB_WID,
        m_axi_gmemB_WUSER,
        m_axi_gmemB_ARVALID,
        m_axi_gmemB_ARREADY,
        m_axi_gmemB_ARADDR,
        m_axi_gmemB_ARID,
        m_axi_gmemB_ARLEN,
        m_axi_gmemB_ARSIZE,
        m_axi_gmemB_ARBURST,
        m_axi_gmemB_ARLOCK,
        m_axi_gmemB_ARCACHE,
        m_axi_gmemB_ARPROT,
        m_axi_gmemB_ARQOS,
        m_axi_gmemB_ARREGION,
        m_axi_gmemB_ARUSER,
        m_axi_gmemB_RVALID,
        m_axi_gmemB_RREADY,
        m_axi_gmemB_RDATA,
        m_axi_gmemB_RLAST,
        m_axi_gmemB_RID,
        m_axi_gmemB_RFIFONUM,
        m_axi_gmemB_RUSER,
        m_axi_gmemB_RRESP,
        m_axi_gmemB_BVALID,
        m_axi_gmemB_BREADY,
        m_axi_gmemB_BRESP,
        m_axi_gmemB_BID,
        m_axi_gmemB_BUSER,
        current_block_M,
        mul_ln110,
        zext_ln119,
        zext_ln110,
        B,
        j_block,
        B_bram_address1,
        B_bram_ce1,
        B_bram_we1,
        B_bram_d1
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmemB_AWVALID;
input   m_axi_gmemB_AWREADY;
output  [63:0] m_axi_gmemB_AWADDR;
output  [0:0] m_axi_gmemB_AWID;
output  [31:0] m_axi_gmemB_AWLEN;
output  [2:0] m_axi_gmemB_AWSIZE;
output  [1:0] m_axi_gmemB_AWBURST;
output  [1:0] m_axi_gmemB_AWLOCK;
output  [3:0] m_axi_gmemB_AWCACHE;
output  [2:0] m_axi_gmemB_AWPROT;
output  [3:0] m_axi_gmemB_AWQOS;
output  [3:0] m_axi_gmemB_AWREGION;
output  [0:0] m_axi_gmemB_AWUSER;
output   m_axi_gmemB_WVALID;
input   m_axi_gmemB_WREADY;
output  [7:0] m_axi_gmemB_WDATA;
output  [0:0] m_axi_gmemB_WSTRB;
output   m_axi_gmemB_WLAST;
output  [0:0] m_axi_gmemB_WID;
output  [0:0] m_axi_gmemB_WUSER;
output   m_axi_gmemB_ARVALID;
input   m_axi_gmemB_ARREADY;
output  [63:0] m_axi_gmemB_ARADDR;
output  [0:0] m_axi_gmemB_ARID;
output  [31:0] m_axi_gmemB_ARLEN;
output  [2:0] m_axi_gmemB_ARSIZE;
output  [1:0] m_axi_gmemB_ARBURST;
output  [1:0] m_axi_gmemB_ARLOCK;
output  [3:0] m_axi_gmemB_ARCACHE;
output  [2:0] m_axi_gmemB_ARPROT;
output  [3:0] m_axi_gmemB_ARQOS;
output  [3:0] m_axi_gmemB_ARREGION;
output  [0:0] m_axi_gmemB_ARUSER;
input   m_axi_gmemB_RVALID;
output   m_axi_gmemB_RREADY;
input  [7:0] m_axi_gmemB_RDATA;
input   m_axi_gmemB_RLAST;
input  [0:0] m_axi_gmemB_RID;
input  [10:0] m_axi_gmemB_RFIFONUM;
input  [0:0] m_axi_gmemB_RUSER;
input  [1:0] m_axi_gmemB_RRESP;
input   m_axi_gmemB_BVALID;
output   m_axi_gmemB_BREADY;
input  [1:0] m_axi_gmemB_BRESP;
input  [0:0] m_axi_gmemB_BID;
input  [0:0] m_axi_gmemB_BUSER;
input  [31:0] current_block_M;
input  [63:0] mul_ln110;
input  [30:0] zext_ln119;
input  [31:0] zext_ln110;
input  [63:0] B;
input  [63:0] j_block;
output  [17:0] B_bram_address1;
output   B_bram_ce1;
output   B_bram_we1;
output  [7:0] B_bram_d1;

reg ap_idle;
reg m_axi_gmemB_ARVALID;
reg m_axi_gmemB_RREADY;
reg B_bram_ce1;
reg B_bram_we1;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
reg   [0:0] or_ln119_reg_391;
reg    ap_block_state3_io;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
reg   [0:0] icmp_ln119_reg_387;
reg   [0:0] icmp_ln119_reg_387_pp0_iter8_reg;
reg    ap_block_state10_pp0_stage0_iter9;
wire    ap_block_state11_pp0_stage0_iter10;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln119_fu_209_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmemB_blk_n_R;
wire    ap_block_pp0_stage0;
reg    gmemB_blk_n_AR;
reg   [0:0] first_iter_0_reg_159;
reg    ap_block_pp0_stage0_11001;
wire   [62:0] zext_ln110_cast_fu_171_p1;
reg   [62:0] zext_ln110_cast_reg_377;
wire   [31:0] zext_ln119_cast_fu_175_p1;
reg   [31:0] zext_ln119_cast_reg_382;
reg   [0:0] icmp_ln119_reg_387_pp0_iter2_reg;
reg   [0:0] icmp_ln119_reg_387_pp0_iter3_reg;
reg   [0:0] icmp_ln119_reg_387_pp0_iter4_reg;
reg   [0:0] icmp_ln119_reg_387_pp0_iter5_reg;
reg   [0:0] icmp_ln119_reg_387_pp0_iter6_reg;
reg   [0:0] icmp_ln119_reg_387_pp0_iter7_reg;
reg   [0:0] icmp_ln119_reg_387_pp0_iter9_reg;
wire   [0:0] or_ln119_fu_235_p2;
reg   [17:0] B_bram_addr_reg_395;
reg   [17:0] B_bram_addr_reg_395_pp0_iter2_reg;
reg   [17:0] B_bram_addr_reg_395_pp0_iter3_reg;
reg   [17:0] B_bram_addr_reg_395_pp0_iter4_reg;
reg   [17:0] B_bram_addr_reg_395_pp0_iter5_reg;
reg   [17:0] B_bram_addr_reg_395_pp0_iter6_reg;
reg   [17:0] B_bram_addr_reg_395_pp0_iter7_reg;
reg   [17:0] B_bram_addr_reg_395_pp0_iter8_reg;
reg   [17:0] B_bram_addr_reg_395_pp0_iter9_reg;
reg   [63:0] gmemB_addr_reg_400;
reg   [7:0] gmemB_addr_1_read_reg_410;
reg   [0:0] ap_phi_mux_first_iter_0_phi_fu_163_p4;
wire    ap_loop_init;
wire   [63:0] zext_ln122_fu_298_p1;
wire   [63:0] add_ln119_2_fu_287_p2;
reg   [17:0] j_fu_84;
wire   [17:0] add_ln120_fu_315_p2;
reg   [30:0] k_1_fu_88;
wire   [30:0] select_ln119_1_fu_249_p3;
reg   [63:0] indvar_flatten17_fu_92;
wire   [63:0] add_ln119_3_fu_214_p2;
wire   [31:0] zext_ln120_fu_200_p1;
wire   [0:0] icmp_ln120_fu_204_p2;
wire   [0:0] xor_ln119_fu_229_p2;
wire   [30:0] add_ln119_fu_223_p2;
wire   [9:0] trunc_ln122_fu_257_p1;
wire   [30:0] mul_ln119_fu_273_p0;
wire   [31:0] mul_ln119_fu_273_p1;
wire   [62:0] mul_ln119_fu_273_p2;
wire   [63:0] zext_ln119_2_fu_278_p1;
wire   [63:0] add_ln119_1_fu_282_p2;
wire   [17:0] tmp_s_fu_261_p3;
wire   [17:0] select_ln119_fu_241_p3;
wire   [17:0] add_ln122_fu_292_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [62:0] mul_ln119_fu_273_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_done_reg = 1'b0;
end

mmult_accel_mul_31ns_32ns_63_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 63 ))
mul_31ns_32ns_63_1_1_U6(
    .din0(mul_ln119_fu_273_p0),
    .din1(mul_ln119_fu_273_p1),
    .dout(mul_ln119_fu_273_p2)
);

mmult_accel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter9_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln119_reg_387 == 1'd0))) begin
        first_iter_0_reg_159 <= 1'd0;
    end else if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        first_iter_0_reg_159 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten17_fu_92 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln119_fu_209_p2 == 1'd0))) begin
            indvar_flatten17_fu_92 <= add_ln119_3_fu_214_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            j_fu_84 <= 18'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln119_fu_209_p2 == 1'd0))) begin
            j_fu_84 <= add_ln120_fu_315_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            k_1_fu_88 <= 31'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln119_fu_209_p2 == 1'd0))) begin
            k_1_fu_88 <= select_ln119_1_fu_249_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln119_fu_209_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        B_bram_addr_reg_395 <= zext_ln122_fu_298_p1;
        or_ln119_reg_391 <= or_ln119_fu_235_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        B_bram_addr_reg_395_pp0_iter2_reg <= B_bram_addr_reg_395;
        B_bram_addr_reg_395_pp0_iter3_reg <= B_bram_addr_reg_395_pp0_iter2_reg;
        B_bram_addr_reg_395_pp0_iter4_reg <= B_bram_addr_reg_395_pp0_iter3_reg;
        B_bram_addr_reg_395_pp0_iter5_reg <= B_bram_addr_reg_395_pp0_iter4_reg;
        B_bram_addr_reg_395_pp0_iter6_reg <= B_bram_addr_reg_395_pp0_iter5_reg;
        B_bram_addr_reg_395_pp0_iter7_reg <= B_bram_addr_reg_395_pp0_iter6_reg;
        B_bram_addr_reg_395_pp0_iter8_reg <= B_bram_addr_reg_395_pp0_iter7_reg;
        B_bram_addr_reg_395_pp0_iter9_reg <= B_bram_addr_reg_395_pp0_iter8_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        icmp_ln119_reg_387_pp0_iter2_reg <= icmp_ln119_reg_387;
        icmp_ln119_reg_387_pp0_iter3_reg <= icmp_ln119_reg_387_pp0_iter2_reg;
        icmp_ln119_reg_387_pp0_iter4_reg <= icmp_ln119_reg_387_pp0_iter3_reg;
        icmp_ln119_reg_387_pp0_iter5_reg <= icmp_ln119_reg_387_pp0_iter4_reg;
        icmp_ln119_reg_387_pp0_iter6_reg <= icmp_ln119_reg_387_pp0_iter5_reg;
        icmp_ln119_reg_387_pp0_iter7_reg <= icmp_ln119_reg_387_pp0_iter6_reg;
        icmp_ln119_reg_387_pp0_iter8_reg <= icmp_ln119_reg_387_pp0_iter7_reg;
        icmp_ln119_reg_387_pp0_iter9_reg <= icmp_ln119_reg_387_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
        icmp_ln119_reg_387 <= icmp_ln119_fu_209_p2;
        zext_ln110_cast_reg_377[31 : 0] <= zext_ln110_cast_fu_171_p1[31 : 0];
        zext_ln119_cast_reg_382[30 : 0] <= zext_ln119_cast_fu_175_p1[30 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln119_reg_387_pp0_iter8_reg == 1'd0))) begin
        gmemB_addr_1_read_reg_410 <= m_axi_gmemB_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((or_ln119_fu_235_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln119_fu_209_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        gmemB_addr_reg_400 <= add_ln119_2_fu_287_p2;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        B_bram_ce1 = 1'b1;
    end else begin
        B_bram_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (icmp_ln119_reg_387_pp0_iter9_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        B_bram_we1 = 1'b1;
    end else begin
        B_bram_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln119_fu_209_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter9_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (icmp_ln119_reg_387 == 1'd0))) begin
        ap_phi_mux_first_iter_0_phi_fu_163_p4 = 1'd0;
    end else begin
        ap_phi_mux_first_iter_0_phi_fu_163_p4 = first_iter_0_reg_159;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (or_ln119_reg_391 == 1'd1))) begin
        gmemB_blk_n_AR = m_axi_gmemB_ARREADY;
    end else begin
        gmemB_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (icmp_ln119_reg_387_pp0_iter8_reg == 1'd0))) begin
        gmemB_blk_n_R = m_axi_gmemB_RVALID;
    end else begin
        gmemB_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (or_ln119_reg_391 == 1'd1))) begin
        m_axi_gmemB_ARVALID = 1'b1;
    end else begin
        m_axi_gmemB_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln119_reg_387_pp0_iter8_reg == 1'd0))) begin
        m_axi_gmemB_RREADY = 1'b1;
    end else begin
        m_axi_gmemB_RREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign B_bram_address1 = B_bram_addr_reg_395_pp0_iter9_reg;

assign B_bram_d1 = gmemB_addr_1_read_reg_410;

assign add_ln119_1_fu_282_p2 = (zext_ln119_2_fu_278_p1 + B);

assign add_ln119_2_fu_287_p2 = (add_ln119_1_fu_282_p2 + j_block);

assign add_ln119_3_fu_214_p2 = (indvar_flatten17_fu_92 + 64'd1);

assign add_ln119_fu_223_p2 = (k_1_fu_88 + 31'd1);

assign add_ln120_fu_315_p2 = (select_ln119_fu_241_p3 + 18'd1);

assign add_ln122_fu_292_p2 = (tmp_s_fu_261_p3 + select_ln119_fu_241_p3);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((m_axi_gmemB_RVALID == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b1) & (icmp_ln119_reg_387_pp0_iter8_reg == 1'd0)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_io)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((m_axi_gmemB_RVALID == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b1) & (icmp_ln119_reg_387_pp0_iter8_reg == 1'd0)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_io)));
end

always @ (*) begin
    ap_block_state10_pp0_stage0_iter9 = ((m_axi_gmemB_RVALID == 1'b0) & (icmp_ln119_reg_387_pp0_iter8_reg == 1'd0));
end

assign ap_block_state11_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state3_io = ((m_axi_gmemB_ARREADY == 1'b0) & (or_ln119_reg_391 == 1'd1));
end

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign icmp_ln119_fu_209_p2 = ((indvar_flatten17_fu_92 == mul_ln110) ? 1'b1 : 1'b0);

assign icmp_ln120_fu_204_p2 = (($signed(zext_ln120_fu_200_p1) < $signed(current_block_M)) ? 1'b1 : 1'b0);

assign m_axi_gmemB_ARADDR = gmemB_addr_reg_400;

assign m_axi_gmemB_ARBURST = 2'd0;

assign m_axi_gmemB_ARCACHE = 4'd0;

assign m_axi_gmemB_ARID = 1'd0;

assign m_axi_gmemB_ARLEN = zext_ln119_cast_reg_382;

assign m_axi_gmemB_ARLOCK = 2'd0;

assign m_axi_gmemB_ARPROT = 3'd0;

assign m_axi_gmemB_ARQOS = 4'd0;

assign m_axi_gmemB_ARREGION = 4'd0;

assign m_axi_gmemB_ARSIZE = 3'd0;

assign m_axi_gmemB_ARUSER = 1'd0;

assign m_axi_gmemB_AWADDR = 64'd0;

assign m_axi_gmemB_AWBURST = 2'd0;

assign m_axi_gmemB_AWCACHE = 4'd0;

assign m_axi_gmemB_AWID = 1'd0;

assign m_axi_gmemB_AWLEN = 32'd0;

assign m_axi_gmemB_AWLOCK = 2'd0;

assign m_axi_gmemB_AWPROT = 3'd0;

assign m_axi_gmemB_AWQOS = 4'd0;

assign m_axi_gmemB_AWREGION = 4'd0;

assign m_axi_gmemB_AWSIZE = 3'd0;

assign m_axi_gmemB_AWUSER = 1'd0;

assign m_axi_gmemB_AWVALID = 1'b0;

assign m_axi_gmemB_BREADY = 1'b0;

assign m_axi_gmemB_WDATA = 8'd0;

assign m_axi_gmemB_WID = 1'd0;

assign m_axi_gmemB_WLAST = 1'b0;

assign m_axi_gmemB_WSTRB = 1'd0;

assign m_axi_gmemB_WUSER = 1'd0;

assign m_axi_gmemB_WVALID = 1'b0;

assign mul_ln119_fu_273_p0 = mul_ln119_fu_273_p00;

assign mul_ln119_fu_273_p00 = select_ln119_1_fu_249_p3;

assign mul_ln119_fu_273_p1 = zext_ln110_cast_reg_377;

assign or_ln119_fu_235_p2 = (xor_ln119_fu_229_p2 | ap_phi_mux_first_iter_0_phi_fu_163_p4);

assign select_ln119_1_fu_249_p3 = ((icmp_ln120_fu_204_p2[0:0] == 1'b1) ? k_1_fu_88 : add_ln119_fu_223_p2);

assign select_ln119_fu_241_p3 = ((icmp_ln120_fu_204_p2[0:0] == 1'b1) ? j_fu_84 : 18'd0);

assign tmp_s_fu_261_p3 = {{trunc_ln122_fu_257_p1}, {8'd0}};

assign trunc_ln122_fu_257_p1 = select_ln119_1_fu_249_p3[9:0];

assign xor_ln119_fu_229_p2 = (icmp_ln120_fu_204_p2 ^ 1'd1);

assign zext_ln110_cast_fu_171_p1 = zext_ln110;

assign zext_ln119_2_fu_278_p1 = mul_ln119_fu_273_p2;

assign zext_ln119_cast_fu_175_p1 = zext_ln119;

assign zext_ln120_fu_200_p1 = j_fu_84;

assign zext_ln122_fu_298_p1 = add_ln122_fu_292_p2;

always @ (posedge ap_clk) begin
    zext_ln110_cast_reg_377[62:32] <= 31'b0000000000000000000000000000000;
    zext_ln119_cast_reg_382[31] <= 1'b0;
end

endmodule //mmult_accel_mmult_accel_Pipeline_VITIS_LOOP_120_2
