-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity mmult_accel_mmult_accel_Pipeline_VITIS_LOOP_120_2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_gmemB_AWVALID : OUT STD_LOGIC;
    m_axi_gmemB_AWREADY : IN STD_LOGIC;
    m_axi_gmemB_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmemB_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmemB_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmemB_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmemB_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmemB_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmemB_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmemB_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmemB_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmemB_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmemB_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmemB_WVALID : OUT STD_LOGIC;
    m_axi_gmemB_WREADY : IN STD_LOGIC;
    m_axi_gmemB_WDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmemB_WSTRB : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmemB_WLAST : OUT STD_LOGIC;
    m_axi_gmemB_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmemB_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmemB_ARVALID : OUT STD_LOGIC;
    m_axi_gmemB_ARREADY : IN STD_LOGIC;
    m_axi_gmemB_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmemB_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmemB_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmemB_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmemB_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmemB_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmemB_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmemB_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmemB_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmemB_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmemB_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmemB_RVALID : IN STD_LOGIC;
    m_axi_gmemB_RREADY : OUT STD_LOGIC;
    m_axi_gmemB_RDATA : IN STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmemB_RLAST : IN STD_LOGIC;
    m_axi_gmemB_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmemB_RFIFONUM : IN STD_LOGIC_VECTOR (10 downto 0);
    m_axi_gmemB_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmemB_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmemB_BVALID : IN STD_LOGIC;
    m_axi_gmemB_BREADY : OUT STD_LOGIC;
    m_axi_gmemB_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmemB_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmemB_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    current_block_M : IN STD_LOGIC_VECTOR (31 downto 0);
    mul_ln110 : IN STD_LOGIC_VECTOR (63 downto 0);
    zext_ln119 : IN STD_LOGIC_VECTOR (30 downto 0);
    zext_ln110 : IN STD_LOGIC_VECTOR (31 downto 0);
    B : IN STD_LOGIC_VECTOR (63 downto 0);
    j_block : IN STD_LOGIC_VECTOR (63 downto 0);
    B_bram_address1 : OUT STD_LOGIC_VECTOR (17 downto 0);
    B_bram_ce1 : OUT STD_LOGIC;
    B_bram_we1 : OUT STD_LOGIC;
    B_bram_d1 : OUT STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of mmult_accel_mmult_accel_Pipeline_VITIS_LOOP_120_2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv18_0 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000000";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv31_1 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000001";
    constant ap_const_lv18_1 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal or_ln119_reg_391 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state3_io : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter6 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter7 : BOOLEAN;
    signal ap_block_state9_pp0_stage0_iter8 : BOOLEAN;
    signal icmp_ln119_reg_387 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln119_reg_387_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state10_pp0_stage0_iter9 : BOOLEAN;
    signal ap_block_state11_pp0_stage0_iter10 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln119_fu_209_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal gmemB_blk_n_R : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal gmemB_blk_n_AR : STD_LOGIC;
    signal first_iter_0_reg_159 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal zext_ln110_cast_fu_171_p1 : STD_LOGIC_VECTOR (62 downto 0);
    signal zext_ln110_cast_reg_377 : STD_LOGIC_VECTOR (62 downto 0);
    signal zext_ln119_cast_fu_175_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln119_cast_reg_382 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln119_reg_387_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln119_reg_387_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln119_reg_387_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln119_reg_387_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln119_reg_387_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln119_reg_387_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln119_reg_387_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln119_fu_235_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal B_bram_addr_reg_395 : STD_LOGIC_VECTOR (17 downto 0);
    signal B_bram_addr_reg_395_pp0_iter2_reg : STD_LOGIC_VECTOR (17 downto 0);
    signal B_bram_addr_reg_395_pp0_iter3_reg : STD_LOGIC_VECTOR (17 downto 0);
    signal B_bram_addr_reg_395_pp0_iter4_reg : STD_LOGIC_VECTOR (17 downto 0);
    signal B_bram_addr_reg_395_pp0_iter5_reg : STD_LOGIC_VECTOR (17 downto 0);
    signal B_bram_addr_reg_395_pp0_iter6_reg : STD_LOGIC_VECTOR (17 downto 0);
    signal B_bram_addr_reg_395_pp0_iter7_reg : STD_LOGIC_VECTOR (17 downto 0);
    signal B_bram_addr_reg_395_pp0_iter8_reg : STD_LOGIC_VECTOR (17 downto 0);
    signal B_bram_addr_reg_395_pp0_iter9_reg : STD_LOGIC_VECTOR (17 downto 0);
    signal gmemB_addr_reg_400 : STD_LOGIC_VECTOR (63 downto 0);
    signal gmemB_addr_1_read_reg_410 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_first_iter_0_phi_fu_163_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal zext_ln122_fu_298_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln119_2_fu_287_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal j_fu_84 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln120_fu_315_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal k_1_fu_88 : STD_LOGIC_VECTOR (30 downto 0);
    signal select_ln119_1_fu_249_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal indvar_flatten17_fu_92 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln119_3_fu_214_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln120_fu_200_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln120_fu_204_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln119_fu_229_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln119_fu_223_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal trunc_ln122_fu_257_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal mul_ln119_fu_273_p0 : STD_LOGIC_VECTOR (30 downto 0);
    signal mul_ln119_fu_273_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln119_fu_273_p2 : STD_LOGIC_VECTOR (62 downto 0);
    signal zext_ln119_2_fu_278_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln119_1_fu_282_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_s_fu_261_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal select_ln119_fu_241_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln122_fu_292_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter9_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal mul_ln119_fu_273_p00 : STD_LOGIC_VECTOR (62 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component mmult_accel_mul_31ns_32ns_63_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (30 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        dout : OUT STD_LOGIC_VECTOR (62 downto 0) );
    end component;


    component mmult_accel_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mul_31ns_32ns_63_1_1_U6 : component mmult_accel_mul_31ns_32ns_63_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 31,
        din1_WIDTH => 32,
        dout_WIDTH => 63)
    port map (
        din0 => mul_ln119_fu_273_p0,
        din1 => mul_ln119_fu_273_p1,
        dout => mul_ln119_fu_273_p2);

    flow_control_loop_pipe_sequential_init_U : component mmult_accel_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter1_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter9_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    first_iter_0_reg_159_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln119_reg_387 = ap_const_lv1_0))) then 
                first_iter_0_reg_159 <= ap_const_lv1_0;
            elsif (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                first_iter_0_reg_159 <= ap_const_lv1_1;
            end if; 
        end if;
    end process;

    indvar_flatten17_fu_92_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten17_fu_92 <= ap_const_lv64_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln119_fu_209_p2 = ap_const_lv1_0))) then 
                    indvar_flatten17_fu_92 <= add_ln119_3_fu_214_p2;
                end if;
            end if; 
        end if;
    end process;

    j_fu_84_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    j_fu_84 <= ap_const_lv18_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln119_fu_209_p2 = ap_const_lv1_0))) then 
                    j_fu_84 <= add_ln120_fu_315_p2;
                end if;
            end if; 
        end if;
    end process;

    k_1_fu_88_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    k_1_fu_88 <= ap_const_lv31_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln119_fu_209_p2 = ap_const_lv1_0))) then 
                    k_1_fu_88 <= select_ln119_1_fu_249_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln119_fu_209_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                B_bram_addr_reg_395 <= zext_ln122_fu_298_p1(18 - 1 downto 0);
                or_ln119_reg_391 <= or_ln119_fu_235_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                B_bram_addr_reg_395_pp0_iter2_reg <= B_bram_addr_reg_395;
                B_bram_addr_reg_395_pp0_iter3_reg <= B_bram_addr_reg_395_pp0_iter2_reg;
                B_bram_addr_reg_395_pp0_iter4_reg <= B_bram_addr_reg_395_pp0_iter3_reg;
                B_bram_addr_reg_395_pp0_iter5_reg <= B_bram_addr_reg_395_pp0_iter4_reg;
                B_bram_addr_reg_395_pp0_iter6_reg <= B_bram_addr_reg_395_pp0_iter5_reg;
                B_bram_addr_reg_395_pp0_iter7_reg <= B_bram_addr_reg_395_pp0_iter6_reg;
                B_bram_addr_reg_395_pp0_iter8_reg <= B_bram_addr_reg_395_pp0_iter7_reg;
                B_bram_addr_reg_395_pp0_iter9_reg <= B_bram_addr_reg_395_pp0_iter8_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
                ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
                icmp_ln119_reg_387_pp0_iter2_reg <= icmp_ln119_reg_387;
                icmp_ln119_reg_387_pp0_iter3_reg <= icmp_ln119_reg_387_pp0_iter2_reg;
                icmp_ln119_reg_387_pp0_iter4_reg <= icmp_ln119_reg_387_pp0_iter3_reg;
                icmp_ln119_reg_387_pp0_iter5_reg <= icmp_ln119_reg_387_pp0_iter4_reg;
                icmp_ln119_reg_387_pp0_iter6_reg <= icmp_ln119_reg_387_pp0_iter5_reg;
                icmp_ln119_reg_387_pp0_iter7_reg <= icmp_ln119_reg_387_pp0_iter6_reg;
                icmp_ln119_reg_387_pp0_iter8_reg <= icmp_ln119_reg_387_pp0_iter7_reg;
                icmp_ln119_reg_387_pp0_iter9_reg <= icmp_ln119_reg_387_pp0_iter8_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
                icmp_ln119_reg_387 <= icmp_ln119_fu_209_p2;
                    zext_ln110_cast_reg_377(31 downto 0) <= zext_ln110_cast_fu_171_p1(31 downto 0);
                    zext_ln119_cast_reg_382(30 downto 0) <= zext_ln119_cast_fu_175_p1(30 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln119_reg_387_pp0_iter8_reg = ap_const_lv1_0))) then
                gmemB_addr_1_read_reg_410 <= m_axi_gmemB_RDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((or_ln119_fu_235_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln119_fu_209_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                gmemB_addr_reg_400 <= add_ln119_2_fu_287_p2;
            end if;
        end if;
    end process;
    zext_ln110_cast_reg_377(62 downto 32) <= "0000000000000000000000000000000";
    zext_ln119_cast_reg_382(31) <= '0';

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    B_bram_address1 <= B_bram_addr_reg_395_pp0_iter9_reg;

    B_bram_ce1_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            B_bram_ce1 <= ap_const_logic_1;
        else 
            B_bram_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    B_bram_d1 <= gmemB_addr_1_read_reg_410;

    B_bram_we1_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001, icmp_ln119_reg_387_pp0_iter9_reg)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (icmp_ln119_reg_387_pp0_iter9_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            B_bram_we1 <= ap_const_logic_1;
        else 
            B_bram_we1 <= ap_const_logic_0;
        end if; 
    end process;

    add_ln119_1_fu_282_p2 <= std_logic_vector(unsigned(zext_ln119_2_fu_278_p1) + unsigned(B));
    add_ln119_2_fu_287_p2 <= std_logic_vector(unsigned(add_ln119_1_fu_282_p2) + unsigned(j_block));
    add_ln119_3_fu_214_p2 <= std_logic_vector(unsigned(indvar_flatten17_fu_92) + unsigned(ap_const_lv64_1));
    add_ln119_fu_223_p2 <= std_logic_vector(unsigned(k_1_fu_88) + unsigned(ap_const_lv31_1));
    add_ln120_fu_315_p2 <= std_logic_vector(unsigned(select_ln119_fu_241_p3) + unsigned(ap_const_lv18_1));
    add_ln122_fu_292_p2 <= std_logic_vector(unsigned(tmp_s_fu_261_p3) + unsigned(select_ln119_fu_241_p3));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter9, m_axi_gmemB_RVALID, ap_block_state3_io, icmp_ln119_reg_387_pp0_iter8_reg)
    begin
                ap_block_pp0_stage0_11001 <= (((m_axi_gmemB_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (icmp_ln119_reg_387_pp0_iter8_reg = ap_const_lv1_0)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_io)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter9, m_axi_gmemB_RVALID, ap_block_state3_io, icmp_ln119_reg_387_pp0_iter8_reg)
    begin
                ap_block_pp0_stage0_subdone <= (((m_axi_gmemB_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (icmp_ln119_reg_387_pp0_iter8_reg = ap_const_lv1_0)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_io)));
    end process;


    ap_block_state10_pp0_stage0_iter9_assign_proc : process(m_axi_gmemB_RVALID, icmp_ln119_reg_387_pp0_iter8_reg)
    begin
                ap_block_state10_pp0_stage0_iter9 <= ((m_axi_gmemB_RVALID = ap_const_logic_0) and (icmp_ln119_reg_387_pp0_iter8_reg = ap_const_lv1_0));
    end process;

        ap_block_state11_pp0_stage0_iter10 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state3_io_assign_proc : process(m_axi_gmemB_ARREADY, or_ln119_reg_391)
    begin
                ap_block_state3_io <= ((m_axi_gmemB_ARREADY = ap_const_logic_0) and (or_ln119_reg_391 = ap_const_lv1_1));
    end process;

        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter6 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage0_iter7 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state9_pp0_stage0_iter8 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, icmp_ln119_fu_209_p2)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln119_fu_209_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter9_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter9_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter1_stage0;

    ap_phi_mux_first_iter_0_phi_fu_163_p4_assign_proc : process(ap_enable_reg_pp0_iter2, icmp_ln119_reg_387, ap_block_pp0_stage0, first_iter_0_reg_159)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln119_reg_387 = ap_const_lv1_0))) then 
            ap_phi_mux_first_iter_0_phi_fu_163_p4 <= ap_const_lv1_0;
        else 
            ap_phi_mux_first_iter_0_phi_fu_163_p4 <= first_iter_0_reg_159;
        end if; 
    end process;


    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    gmemB_blk_n_AR_assign_proc : process(ap_enable_reg_pp0_iter2, m_axi_gmemB_ARREADY, or_ln119_reg_391, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (or_ln119_reg_391 = ap_const_lv1_1))) then 
            gmemB_blk_n_AR <= m_axi_gmemB_ARREADY;
        else 
            gmemB_blk_n_AR <= ap_const_logic_1;
        end if; 
    end process;


    gmemB_blk_n_R_assign_proc : process(ap_enable_reg_pp0_iter9, m_axi_gmemB_RVALID, icmp_ln119_reg_387_pp0_iter8_reg, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln119_reg_387_pp0_iter8_reg = ap_const_lv1_0))) then 
            gmemB_blk_n_R <= m_axi_gmemB_RVALID;
        else 
            gmemB_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;

    icmp_ln119_fu_209_p2 <= "1" when (indvar_flatten17_fu_92 = mul_ln110) else "0";
    icmp_ln120_fu_204_p2 <= "1" when (signed(zext_ln120_fu_200_p1) < signed(current_block_M)) else "0";
    m_axi_gmemB_ARADDR <= gmemB_addr_reg_400;
    m_axi_gmemB_ARBURST <= ap_const_lv2_0;
    m_axi_gmemB_ARCACHE <= ap_const_lv4_0;
    m_axi_gmemB_ARID <= ap_const_lv1_0;
    m_axi_gmemB_ARLEN <= zext_ln119_cast_reg_382;
    m_axi_gmemB_ARLOCK <= ap_const_lv2_0;
    m_axi_gmemB_ARPROT <= ap_const_lv3_0;
    m_axi_gmemB_ARQOS <= ap_const_lv4_0;
    m_axi_gmemB_ARREGION <= ap_const_lv4_0;
    m_axi_gmemB_ARSIZE <= ap_const_lv3_0;
    m_axi_gmemB_ARUSER <= ap_const_lv1_0;

    m_axi_gmemB_ARVALID_assign_proc : process(ap_enable_reg_pp0_iter2, or_ln119_reg_391, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (or_ln119_reg_391 = ap_const_lv1_1))) then 
            m_axi_gmemB_ARVALID <= ap_const_logic_1;
        else 
            m_axi_gmemB_ARVALID <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmemB_AWADDR <= ap_const_lv64_0;
    m_axi_gmemB_AWBURST <= ap_const_lv2_0;
    m_axi_gmemB_AWCACHE <= ap_const_lv4_0;
    m_axi_gmemB_AWID <= ap_const_lv1_0;
    m_axi_gmemB_AWLEN <= ap_const_lv32_0;
    m_axi_gmemB_AWLOCK <= ap_const_lv2_0;
    m_axi_gmemB_AWPROT <= ap_const_lv3_0;
    m_axi_gmemB_AWQOS <= ap_const_lv4_0;
    m_axi_gmemB_AWREGION <= ap_const_lv4_0;
    m_axi_gmemB_AWSIZE <= ap_const_lv3_0;
    m_axi_gmemB_AWUSER <= ap_const_lv1_0;
    m_axi_gmemB_AWVALID <= ap_const_logic_0;
    m_axi_gmemB_BREADY <= ap_const_logic_0;

    m_axi_gmemB_RREADY_assign_proc : process(ap_enable_reg_pp0_iter9, icmp_ln119_reg_387_pp0_iter8_reg, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln119_reg_387_pp0_iter8_reg = ap_const_lv1_0))) then 
            m_axi_gmemB_RREADY <= ap_const_logic_1;
        else 
            m_axi_gmemB_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmemB_WDATA <= ap_const_lv8_0;
    m_axi_gmemB_WID <= ap_const_lv1_0;
    m_axi_gmemB_WLAST <= ap_const_logic_0;
    m_axi_gmemB_WSTRB <= ap_const_lv1_0;
    m_axi_gmemB_WUSER <= ap_const_lv1_0;
    m_axi_gmemB_WVALID <= ap_const_logic_0;
    mul_ln119_fu_273_p0 <= mul_ln119_fu_273_p00(31 - 1 downto 0);
    mul_ln119_fu_273_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln119_1_fu_249_p3),63));
    mul_ln119_fu_273_p1 <= zext_ln110_cast_reg_377(32 - 1 downto 0);
    or_ln119_fu_235_p2 <= (xor_ln119_fu_229_p2 or ap_phi_mux_first_iter_0_phi_fu_163_p4);
    select_ln119_1_fu_249_p3 <= 
        k_1_fu_88 when (icmp_ln120_fu_204_p2(0) = '1') else 
        add_ln119_fu_223_p2;
    select_ln119_fu_241_p3 <= 
        j_fu_84 when (icmp_ln120_fu_204_p2(0) = '1') else 
        ap_const_lv18_0;
    tmp_s_fu_261_p3 <= (trunc_ln122_fu_257_p1 & ap_const_lv8_0);
    trunc_ln122_fu_257_p1 <= select_ln119_1_fu_249_p3(10 - 1 downto 0);
    xor_ln119_fu_229_p2 <= (icmp_ln120_fu_204_p2 xor ap_const_lv1_1);
    zext_ln110_cast_fu_171_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln110),63));
    zext_ln119_2_fu_278_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln119_fu_273_p2),64));
    zext_ln119_cast_fu_175_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln119),32));
    zext_ln120_fu_200_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(j_fu_84),32));
    zext_ln122_fu_298_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln122_fu_292_p2),64));
end behav;
