-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity mmult_accel_mmult_accel_Pipeline_copy_A_VITIS_LOOP_97_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_gmemA_AWVALID : OUT STD_LOGIC;
    m_axi_gmemA_AWREADY : IN STD_LOGIC;
    m_axi_gmemA_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmemA_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmemA_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmemA_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmemA_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmemA_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmemA_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmemA_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmemA_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmemA_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmemA_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmemA_WVALID : OUT STD_LOGIC;
    m_axi_gmemA_WREADY : IN STD_LOGIC;
    m_axi_gmemA_WDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmemA_WSTRB : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmemA_WLAST : OUT STD_LOGIC;
    m_axi_gmemA_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmemA_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmemA_ARVALID : OUT STD_LOGIC;
    m_axi_gmemA_ARREADY : IN STD_LOGIC;
    m_axi_gmemA_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmemA_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmemA_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmemA_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmemA_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmemA_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmemA_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmemA_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmemA_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmemA_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmemA_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmemA_RVALID : IN STD_LOGIC;
    m_axi_gmemA_RREADY : OUT STD_LOGIC;
    m_axi_gmemA_RDATA : IN STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmemA_RLAST : IN STD_LOGIC;
    m_axi_gmemA_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmemA_RFIFONUM : IN STD_LOGIC_VECTOR (10 downto 0);
    m_axi_gmemA_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmemA_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmemA_BVALID : IN STD_LOGIC;
    m_axi_gmemA_BREADY : OUT STD_LOGIC;
    m_axi_gmemA_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmemA_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmemA_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    A : IN STD_LOGIC_VECTOR (63 downto 0);
    K : IN STD_LOGIC_VECTOR (31 downto 0);
    mul_ln96_1 : IN STD_LOGIC_VECTOR (63 downto 0);
    A_bram_address1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    A_bram_ce1 : OUT STD_LOGIC;
    A_bram_we1 : OUT STD_LOGIC;
    A_bram_d1 : OUT STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of mmult_accel_mmult_accel_Pipeline_copy_A_VITIS_LOOP_97_1 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv31_1 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000001";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal icmp_ln96_reg_299 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln96_fu_149_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal gmemA_blk_n_R : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal add_ln99_fu_232_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln99_reg_303 : STD_LOGIC_VECTOR (15 downto 0);
    signal gmemA_addr_read_reg_308 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_condition_exit_pp0_iter2_stage0 : STD_LOGIC;
    signal zext_ln99_fu_254_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal k_fu_74 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln97_fu_238_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal i_fu_78 : STD_LOGIC_VECTOR (30 downto 0);
    signal select_ln96_1_fu_194_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal indvar_flatten_fu_82 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln96_1_fu_154_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln97_fu_168_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln97_fu_172_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln96_fu_180_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal trunc_ln99_1_fu_206_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln99_fu_202_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_s_fu_210_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_32_fu_218_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal sub_ln99_fu_226_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln96_fu_186_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component mmult_accel_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component mmult_accel_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter1_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter2_stage0)) then 
                    ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    i_fu_78_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    i_fu_78 <= ap_const_lv31_0;
                elsif (((icmp_ln96_reg_299 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
                    i_fu_78 <= select_ln96_1_fu_194_p3;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten_fu_82_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten_fu_82 <= ap_const_lv64_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln96_fu_149_p2 = ap_const_lv1_0))) then 
                    indvar_flatten_fu_82 <= add_ln96_1_fu_154_p2;
                end if;
            end if; 
        end if;
    end process;

    k_fu_74_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    k_fu_74 <= ap_const_lv16_0;
                elsif (((icmp_ln96_reg_299 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
                    k_fu_74 <= add_ln97_fu_238_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln96_reg_299 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                add_ln99_reg_303 <= add_ln99_fu_232_p2;
                gmemA_addr_read_reg_308 <= m_axi_gmemA_RDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
                icmp_ln96_reg_299 <= icmp_ln96_fu_149_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    A_bram_address1 <= zext_ln99_fu_254_p1(16 - 1 downto 0);

    A_bram_ce1_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            A_bram_ce1 <= ap_const_logic_1;
        else 
            A_bram_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    A_bram_d1 <= gmemA_addr_read_reg_308;

    A_bram_we1_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            A_bram_we1 <= ap_const_logic_1;
        else 
            A_bram_we1 <= ap_const_logic_0;
        end if; 
    end process;

    add_ln96_1_fu_154_p2 <= std_logic_vector(unsigned(indvar_flatten_fu_82) + unsigned(ap_const_lv64_1));
    add_ln96_fu_180_p2 <= std_logic_vector(unsigned(i_fu_78) + unsigned(ap_const_lv31_1));
    add_ln97_fu_238_p2 <= std_logic_vector(unsigned(select_ln96_fu_186_p3) + unsigned(ap_const_lv16_1));
    add_ln99_fu_232_p2 <= std_logic_vector(unsigned(sub_ln99_fu_226_p2) + unsigned(select_ln96_fu_186_p3));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter2, m_axi_gmemA_RVALID, icmp_ln96_reg_299)
    begin
                ap_block_pp0_stage0_11001 <= ((icmp_ln96_reg_299 = ap_const_lv1_0) and (m_axi_gmemA_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter2, m_axi_gmemA_RVALID, icmp_ln96_reg_299)
    begin
                ap_block_pp0_stage0_subdone <= ((icmp_ln96_reg_299 = ap_const_lv1_0) and (m_axi_gmemA_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1));
    end process;

        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state3_pp0_stage0_iter2_assign_proc : process(m_axi_gmemA_RVALID, icmp_ln96_reg_299)
    begin
                ap_block_state3_pp0_stage0_iter2 <= ((icmp_ln96_reg_299 = ap_const_lv1_0) and (m_axi_gmemA_RVALID = ap_const_logic_0));
    end process;

        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, icmp_ln96_fu_149_p2)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln96_fu_149_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter2_stage0_assign_proc : process(ap_enable_reg_pp0_iter2, icmp_ln96_reg_299, ap_block_pp0_stage0_subdone)
    begin
        if (((icmp_ln96_reg_299 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter2_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter2_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter1_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    gmemA_blk_n_R_assign_proc : process(ap_enable_reg_pp0_iter2, m_axi_gmemA_RVALID, icmp_ln96_reg_299, ap_block_pp0_stage0)
    begin
        if (((icmp_ln96_reg_299 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            gmemA_blk_n_R <= m_axi_gmemA_RVALID;
        else 
            gmemA_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;

    icmp_ln96_fu_149_p2 <= "1" when (indvar_flatten_fu_82 = mul_ln96_1) else "0";
    icmp_ln97_fu_172_p2 <= "1" when (signed(zext_ln97_fu_168_p1) < signed(K)) else "0";
    m_axi_gmemA_ARADDR <= ap_const_lv64_0;
    m_axi_gmemA_ARBURST <= ap_const_lv2_0;
    m_axi_gmemA_ARCACHE <= ap_const_lv4_0;
    m_axi_gmemA_ARID <= ap_const_lv1_0;
    m_axi_gmemA_ARLEN <= ap_const_lv32_0;
    m_axi_gmemA_ARLOCK <= ap_const_lv2_0;
    m_axi_gmemA_ARPROT <= ap_const_lv3_0;
    m_axi_gmemA_ARQOS <= ap_const_lv4_0;
    m_axi_gmemA_ARREGION <= ap_const_lv4_0;
    m_axi_gmemA_ARSIZE <= ap_const_lv3_0;
    m_axi_gmemA_ARUSER <= ap_const_lv1_0;
    m_axi_gmemA_ARVALID <= ap_const_logic_0;
    m_axi_gmemA_AWADDR <= ap_const_lv64_0;
    m_axi_gmemA_AWBURST <= ap_const_lv2_0;
    m_axi_gmemA_AWCACHE <= ap_const_lv4_0;
    m_axi_gmemA_AWID <= ap_const_lv1_0;
    m_axi_gmemA_AWLEN <= ap_const_lv32_0;
    m_axi_gmemA_AWLOCK <= ap_const_lv2_0;
    m_axi_gmemA_AWPROT <= ap_const_lv3_0;
    m_axi_gmemA_AWQOS <= ap_const_lv4_0;
    m_axi_gmemA_AWREGION <= ap_const_lv4_0;
    m_axi_gmemA_AWSIZE <= ap_const_lv3_0;
    m_axi_gmemA_AWUSER <= ap_const_lv1_0;
    m_axi_gmemA_AWVALID <= ap_const_logic_0;
    m_axi_gmemA_BREADY <= ap_const_logic_0;

    m_axi_gmemA_RREADY_assign_proc : process(ap_enable_reg_pp0_iter2, icmp_ln96_reg_299, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln96_reg_299 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            m_axi_gmemA_RREADY <= ap_const_logic_1;
        else 
            m_axi_gmemA_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmemA_WDATA <= ap_const_lv8_0;
    m_axi_gmemA_WID <= ap_const_lv1_0;
    m_axi_gmemA_WLAST <= ap_const_logic_0;
    m_axi_gmemA_WSTRB <= ap_const_lv1_0;
    m_axi_gmemA_WUSER <= ap_const_lv1_0;
    m_axi_gmemA_WVALID <= ap_const_logic_0;
    select_ln96_1_fu_194_p3 <= 
        i_fu_78 when (icmp_ln97_fu_172_p2(0) = '1') else 
        add_ln96_fu_180_p2;
    select_ln96_fu_186_p3 <= 
        k_fu_74 when (icmp_ln97_fu_172_p2(0) = '1') else 
        ap_const_lv16_0;
    sub_ln99_fu_226_p2 <= std_logic_vector(unsigned(tmp_s_fu_210_p3) - unsigned(tmp_32_fu_218_p3));
    tmp_32_fu_218_p3 <= (trunc_ln99_fu_202_p1 & ap_const_lv8_0);
    tmp_s_fu_210_p3 <= (trunc_ln99_1_fu_206_p1 & ap_const_lv10_0);
    trunc_ln99_1_fu_206_p1 <= select_ln96_1_fu_194_p3(6 - 1 downto 0);
    trunc_ln99_fu_202_p1 <= select_ln96_1_fu_194_p3(8 - 1 downto 0);
    zext_ln97_fu_168_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(k_fu_74),32));
    zext_ln99_fu_254_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln99_reg_303),64));
end behav;
